### ISSUE TITLE
define target data column definitions in config file

### ISSUE THREAD

**Issue by zkamvar** [hubverse-org/hub-dashboard-predtimechart#36]
instead of having hard-coded names for date, value, and location, we could implement it as a dictionary in the config file like we do the location mappings. For example: 

```yaml
target_data_cols:
  date: date_onset
  value: observed
  location: province
```

_Originally posted by @zkamvar in https://github.com/hubverse-org/hub-dashboard-predtimechart/pull/35#pullrequestreview-2476272041_
